name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST1 }}
          username: ${{ secrets.EC2_USER1 }}
          key: ${{ secrets.EC2_KEY1 }}
          script: |
            cd /var/www/landing-page-template-reactjs
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx
